name: CI Build and Test

on: 
  push:
    branches: 
    - main
    paths:
    - sources/**
  pull_request:
    branches: 
    - master
    paths:
    - sources/**

jobs:
  Font-ci-job:
    runs-on: ubuntu-latest
    name: CI VF ttf
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # - name: Python build dependency cache lookup
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     # Check for requirements file cache hit
          # key: ${{ runner.os }}-pip-${{ hashFiles('${{ steps.config.outputs.dependpath }}') }}
      # - name: Install Python build dependencies
      #   uses: py-actions/py-dependency-install@v4
      #   with:
      #     update-wheel: "true"
      #     update-setuptools: "true"
      - name: Install dependencies
        # The --pre flag below will ensure we use the latest Font Bakery pre-releases
        # and benefit from its newest checks:
        run: |
          sudo apt install libharfbuzz-dev libharfbuzz-bin libglib2.0-dev libcairo2-dev
          python -m pip install --upgrade pip
          pip install freetype-py
          pip install --pre fontbakery
          pip install gftools
      - name: Install ttfautohint
        run: |
          sudo apt-get update
          sudo apt-get install ttfautohint
      - name: Build fonts
        id: build_fonts
        run: gftools builder sources/config.yaml
      - name: Upload Fonts
        uses: actions/upload-artifact@v3
        with:
          name: Geologica-Font
          path: fonts/
      - name: Make Fontbakery Report
        uses: f-actions/font-bakery@v2
        with:
          version: "latest"
          subcmd: "check-googlefonts"
          args: "-C --succinct --loglevel WARN --ghm fonts/report.md"
          path: "fonts/variable/*.ttf"